### PR TITLE
initial work on pattern to proxy

### PR DESCRIPTION
**Pull request by jeffreyrosenbluth**
## I thinks this is ready.

What is the easiest way to test this?

### CODE REVIEW

**Comment by andygill** [comment]
We have a test that is used to build the wiki. If you go into wiki-suite, and type `make`, then type 

    ./dist/build/wiki-suite/wiki-suite Pattern

this *should* test what you are adding.

**Comment by jeffreyrosenbluth** [comment]
great, i'll give it a go

**Comment by jeffreyrosenbluth** [comment]
I think this is what you want

**Comment by jeffreyrosenbluth** [comment]
by the way, I strongly suspect that `newImage` and `drawImage` could be handled as proxies as well.
I'm just not sure how to do this in the context of Scotty.

**Comment by andygill** [comment]
Thanks! I'll test and merge tonight.

**Comment by andygill** [comment]
Thanks! It passes the tests just fine.

**Pull request merged**
