### PR TITLE
Adding websockets enabled kansas-comet.

### PR DESCRIPTION
**Pull request by moizjv**
@RyanGlScott  please review blank-canvas changes. 

- Only major change is the way kansas-comet is called. 
- Other changes are just modularization of code. 
- Depends on updated version of kansas-comet.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Here's some issues I've noticed with websockets enabled:

* Refreshing the browser when a `blank-canvas` app is running evidently triggers some Haskell exception, since my terminal always prints

 ```
 CloseRequest 1001 ""
 "Exception in blank-canvas application:"
 send: invalid argument (Bad file descriptor)
 blank-canvas-mark: send: invalid argument (Bad file descriptor)
 ```
* The benchmark suite behaves oddly in the presence of websockets. On Chrome, certain tests (e.g., `Bézier` and `CirclesRandomSize` render on the browser for about 5 seconds longer than they should (e.g., the terminal indicates that it has begun `benchmarking CirclesUniformSize` well before `CirclesRandomSize` has finished). A similar effect can be observed on Firefox, except that it has been significantly slowed down to the point where it no longer looks like animation.

**Comment by moizjv** [comment]
@RyanGlScott ,

Thank you for testing websockets enabled blank-canvas. For the first issue of when refreshing a webpage, this is what is happening it is disconnecting the established websocket connection abruptly hence the server spits out exception, but it reconnects a new websocket connection after refresh. 

I did not test it on linux and browsers. I tested on mac and google chrome most of the time and it works pretty smoothly. let me look into what can cause a lag this week end.

**Comment by moizjv** [comment]
@RyanGlScott  I did a quick run of benchmarks on my mac every thing runs smoothly for google chrome. For firefox there is some lag for Bezier and Rave try commenting those two benchmarks and run it. So once we narrow down the problem. Also i hope you are running using `http://localhost:3000/?height=600&width=800` . Bouncing ball example runs fine in both the browsers for me. 
Again thanks for taking time and looking into this.

**Comment by RyanGlScott** [comment]
I tried changing the size of the canvas using `http://localhost:3000/?height=600&width=800`, but it didn't have any effect on the benchmarks.

On Linux, the benchmarks that are stalling my browsers are `Bézier`, `CirclesRandomSize`, `CirclesUniformSize`, and `FillText`.
* On Chromium, the effect is that the tests run for longer than expected. `Bézier` runs for about 9 seconds after the terminal indicates the test is over, and `CirclesRandomSize`, `CirclesUniformSize`, and `FillText` run for about 1-2 seconds longer.
* On Firefox, the tests completely stall any JavaScript activity on the browser, making Firefox virtually unusable.

Also, is there any way to catch the exception that's thrown when a websocket is disconnected due to a refresh? It's a bit jarring to see that, especially for those who aren't familiar with `kansas-comet`'s internals.

**Comment by moizjv** [comment]
@RyanGlScott so what i am planning to do is to get a virtual box for Linux and investigate deeper. What is configuration for your linux box so i can reproduce it here, it works pretty smoothly for me on mac, specially chrome. Also at the same time i would code a small node websocket application with similar application to js metric and see if its problem with websockets. I will close this pull request for now until i have better version working for linux.

**Comment by RyanGlScott** [comment]
My ITTC computer's configuration is as follows:

* Fedora 20 (Heisenbug), 64-bit
* 5.8 GB RAM
* Intel Core i7 CPU (8 cores) at 2.67 GHz
* Firefox 35
* Chromium 38.0.2125.101

**Comment by andygill** [comment]
Did we ever solve this?

**Comment by RyanGlScott** [comment]
I'm not sure. I'm still not positive if the `blank-canvas-mark` problems were due to the computer itself lagging or due to websockets. Since the benchmarks were changed recently, I suppose I should retry and see how it works now. I'd also like to see if it's possible to suppress the errors that appear on the console whenever the browser is refreshed, but I suppose I could live without that.

**Comment by moizjv** [comment]
Yes i need to take some time out to look into this again. I want to update to latest version of websockets, i think that would require an update on its dependencies.

**Pull request closed without merging**
